behind-the-rescue:
  petango:
    auth-key: auth_key
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
hibernate:
  dialect: org.hibernate.dialect.H2Dialect