behind-the-rescue:
  petango:
    site: Stray Animal Adoption Program
    auth-key: ${PETANGO_API_AUTH_KEY}
  allowed-origins: https://behindtherescue.com,https://www.behindtherescue.com
server:
  port: ${PORT}
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: .*
    rate-limits:
    - bandwidths:
      - capacity: 100
        time: 1
        unit: minutes