package com.adoptastray.behindtherescue.web.cratereservation.message

import com.adoptastray.behindtherescue.application.cratereservation.dto.ListCrateReservationDto

class GetCrateReservationsResponse(val crateReservations: List<ListCrateReservationDto>)