package com.adoptastray.behindtherescue.web.cratereservation.message

import com.adoptastray.behindtherescue.application.cratereservation.dto.CrateReservationDto

class ReserveCrateResponse(val crateReservation: CrateReservationDto)